#!/usr/bin/env python3
"""
Generate the synthetic sample recording shipped with this repository.

    python scripts/make_sample.py

Writes sample/SYNTH01.{inf,bin} in the same format a GE cath-lab export uses, so the
viewer and the cleaning pipeline can be tried without any patient data. Everything here
is computed from sine and Gaussian terms -- there is no recording behind it.

The file deliberately contains the two artefacts real exports carry, so the cleaning
controls have something to act on:
  * a flush that drives AO past the +409.4 mmHg full scale and wraps to about -12700
  * a burst of ECG saturation on V2, driven by simulated electrode motion
plus a transducer-off period at each end and a transient damped-pressure episode.
"""
import numpy as np
from pathlib import Path

FS, SECS = 240, 150
N = FS * SECS
LAB = ['I', 'II', 'III', 'aVR', 'aVL', 'aVF',
       'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'PCW', 'AO']
C = len(LAB)
ECG_LSB, PRESS_LSB = 10.0 / 4096, 0.2      # 12-bit over +/-5 mV, and 0.2 mmHg
OUT = Path(__file__).resolve().parent.parent / 'sample'

rng = np.random.default_rng(7)
t = np.arange(N) / FS

# ---- beat timing: 68 bpm drifting to 82, with a little respiratory variation -------
hr = 68 + 14 * np.clip((t - 60) / 60, 0, 1) + 1.5 * np.sin(2 * np.pi * t / 12)
phase = np.cumsum(hr / 60 / FS)            # beats elapsed
frac = phase % 1.0                         # position within the beat

def bump(centre, width, amp):
    d = (frac - centre + 0.5) % 1.0 - 0.5  # wrap-safe distance
    return amp * np.exp(-0.5 * (d / width) ** 2)

# P, Q, R, S, T
beat = (bump(.16, .022, .12) + bump(.29, .006, -.13) + bump(.31, .008, 1.0)
        + bump(.34, .008, -.26) + bump(.55, .045, .30))

x = np.zeros((N, C))
amp = dict(zip(LAB[:12], [.62, 1.00, .48, -.80, .22, .70, -.55, 1.35, 1.10, .92, .74, .52]))
for i, l in enumerate(LAB[:12]):
    wander = 0.10 * np.sin(2 * np.pi * 0.23 * t + i) + 0.05 * np.sin(2 * np.pi * 0.08 * t)
    x[:, i] = beat * amp[l] + wander + 0.005 * rng.standard_normal(N)

# ---- arterial and wedge pressures ---------------------------------------------------
ao = (bump(.34, .045, 1.00) + bump(.47, .050, 0.34) + bump(.75, .220, 0.20))
sys_, dia = 128.0, 72.0
x[:, 13] = dia + (sys_ - dia) * ao + 0.25 * rng.standard_normal(N)
x[:, 12] = (9.5 + 3.2 * np.sin(2 * np.pi * phase) + 1.8 * np.sin(4 * np.pi * phase)
            + 1.2 * np.sin(2 * np.pi * t / 4.5) + 0.18 * rng.standard_normal(N))

# ---- transducers not live at the start and the end ----------------------------------
x[:8 * FS, 12] = 0.4
x[:8 * FS, 13] = -3.0
x[-6 * FS:, 12] = 0.4
x[-6 * FS:, 13] = -3.0

# ---- a damped-pressure episode, as a guide catheter would cause ---------------------
a, b = 100 * FS, 118 * FS
ramp = np.minimum(1.0, np.minimum(np.arange(b - a), (b - a) - np.arange(b - a)) / (2 * FS))
mid = x[a:b, 13].mean()
x[a:b, 13] = mid + (x[a:b, 13] - mid) * (1 - 0.72 * ramp) - 38 * ramp

# ---- a flush: AO past full scale, stored as a 16-bit wrap ---------------------------
f0 = 30 * FS
flush = np.concatenate([np.linspace(130, 520, 22), np.linspace(520, 130, 26)])
x[f0:f0 + flush.size, 13] = flush

# ---- electrode motion drives the precordial leads into the rail ---------------------
# long enough to read as a rail rather than as a couple of tall beats, which is what a
# real record looks like (V2 sits at the rail 15% of the time in the reference case)
for ch, (m0, m1, amp, off) in {7:  (58, 72, 6.5, 2.0),      # V2
                               9:  (61, 68, 5.0, 1.2)}.items():   # V4
    s0, s1 = m0 * FS, m1 * FS
    x[s0:s1, ch] += amp * np.sin(2 * np.pi * 0.8 * t[s0:s1]) + off

# ---- quantise to the recorder's steps, then apply the overflow ----------------------
x[:, :12] = np.round(x[:, :12] / ECG_LSB) * ECG_LSB
x[:, :12] = np.clip(x[:, :12], -2047 * ECG_LSB, 2047 * ECG_LSB)      # hard ADC rail
x[:, 12:] = np.round(x[:, 12:] / PRESS_LSB) * PRESS_LSB
over = x[:, 12:] > 2047 * PRESS_LSB
x[:, 12:][over] -= 65536 * PRESS_LSB                                  # the wrap

OUT.mkdir(exist_ok=True)
(OUT / 'SYNTH01.bin').write_bytes(x.astype('<f8').tobytes())
inf = (
    "Patient = SYNTHETIC, Sample\r\n"
    "Description = generated by scripts/make_sample.py - not a real recording\r\n"
    "Date = 1/1/2026 12:00:00 PM \r\n"
    f"Number of Channel = {C} \r\n"
    f"Points for Each Channel = {N} \r\n"
    f"Data Sampling Rate = {FS} points/second \r\n"
    "Start Time = 1/1/2026 9:00:00 AM\r\n"
    f"Stop Time = 1/1/2026 9:0{SECS // 60}:{SECS % 60:02d} AM\r\n"
    "Units: mmHg for pressure and mV for all others \r\n"
    "Channel Number  Channel Label\r\n"
    + "".join(f"{i+1}              {l}\r\n" for i, l in enumerate(LAB))
)
(OUT / 'SYNTH01.inf').write_text(inf, encoding='latin-1')

print(f"wrote {OUT/'SYNTH01.bin'}  ({N*C*8:,} bytes = {N} x {C} x 8)")
print(f"wrote {OUT/'SYNTH01.inf'}")
print(f"  {SECS} s, {C} channels @ {FS} Hz")
print(f"  AO range {x[:,13].min():.1f} .. {x[:,13].max():.1f} mmHg (wrapped samples: {int(over.sum())})")
for ch in (7, 9):
    n_rail = int((np.abs(x[:, ch]) >= 2047 * ECG_LSB - 1e-9).sum())
    print(f"  {LAB[ch]} samples at the rail: {n_rail} ({100*n_rail/N:.1f}%)")
